name: ci

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  test:
    name: OTP ${{matrix.otp_vsn}}
    strategy:
      matrix:
        otp_vsn: ['28', '27', '26']
        rebar_vsn: ['3.25.0']
    runs-on: 'ubuntu-24.04'
    env:
      OTPVER: ${{ matrix.otp }}
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ matrix.otp_vsn }}
          rebar3-version: ${{ matrix.rebar_vsn }}
      - uses: actions/cache@v4
        name: Cache
        with:
          path: _build
          key: ${{ runner.os }}-build-${{ matrix.otp_vsn }}-${{ hashFiles(format('rebar.lock')) }}-1
          restore-keys: ${{ runner.os }}-build-${{ matrix.otp_vsn }}-1-
      - run: rebar3 as test compile -d
      - run: rebar3 eunit
      - run: rebar3 dialyzer
      - run: rebar3 as test codecov analyze
      - run: gcov -o c_src exml
      - uses: codecov/codecov-action@v5
        with:
          name: Upload coverage reports to Codecov
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          verbose: true
